package gui;

import java.awt.BorderLayout;

public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();   
 
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        listArtistFormItem = new javax.swing.JMenuItem();
        listMusicGroupFormItem = new javax.swing.JMenuItem();
        listMusicGroupAlbumFormItem = new javax.swing.JMenuItem();
        listArtistAlbumFormItem = new javax.swing.JMenuItem();
        listPlayListFormItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Σύστημα Ραδιοφωνικού Σταθμού");

        jMenu1.setText("Μενού");

        jMenu3.setText("1-Διαχείριση Αρχείων");

        listArtistFormItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.ALT_MASK));
        listArtistFormItem.setText("Καλλιτέχνες");
        listArtistFormItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listArtistFormItemActionPerformed(evt);
            }
        });
        jMenu3.add(listArtistFormItem);

        listMusicGroupFormItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        listMusicGroupFormItem.setText("Συγκροτήματα");
        listMusicGroupFormItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listMusicGroupFormItemActionPerformed(evt);
            }
        });
        jMenu3.add(listMusicGroupFormItem);

        listMusicGroupAlbumFormItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        listMusicGroupAlbumFormItem.setText("Άλμπουμ Συγκροτημάτων");
        listMusicGroupAlbumFormItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listMusicGroupAlbumFormItemActionPerformed(evt);
            }
        });
        jMenu3.add(listMusicGroupAlbumFormItem);

        listArtistAlbumFormItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        listArtistAlbumFormItem.setText("Άλμπουμ Καλλιτεχνών");
        listArtistAlbumFormItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listArtistAlbumFormItemActionPerformed(evt);
            }
        });
        jMenu3.add(listArtistAlbumFormItem);

        jMenu1.add(jMenu3);

        listPlayListFormItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_MASK));
        listPlayListFormItem.setText("2-Λίστες Τραγουδιών");
        listPlayListFormItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listPlayListFormItemActionPerformed(evt);
            }
        });
        jMenu1.add(listPlayListFormItem);
        jMenu1.add(jSeparator1);

        exitItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.ALT_MASK));
        exitItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.gif"))); // NOI18N
        exitItem.setText("3-Έξοδος");
        exitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitItemActionPerformed(evt);
            }
        });
        jMenu1.add(exitItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(416, 338));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void listMusicGroupFormItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listMusicGroupFormItemActionPerformed
        
        ListMusicGroupForm lmgf = new ListMusicGroupForm();
        
        jMenu1.setEnabled(false);
        
        add(lmgf, BorderLayout.CENTER);
        
        pack();
    }//GEN-LAST:event_listMusicGroupFormItemActionPerformed

    private void exitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitItemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitItemActionPerformed

    private void listArtistFormItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listArtistFormItemActionPerformed
        
        ListArtistForm laf = new ListArtistForm();
        
        jMenu1.setEnabled(false);
        
        add(laf,BorderLayout.CENTER);
        
        pack();
    }//GEN-LAST:event_listArtistFormItemActionPerformed

    private void listMusicGroupAlbumFormItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listMusicGroupAlbumFormItemActionPerformed
        
        ListMusicGroupAlbumForm lmgaf = new ListMusicGroupAlbumForm();
        
        jMenu1.setEnabled(false);
        
        add(lmgaf,BorderLayout.CENTER);
        
        pack(); 
    }//GEN-LAST:event_listMusicGroupAlbumFormItemActionPerformed

    private void listArtistAlbumFormItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listArtistAlbumFormItemActionPerformed
        
        ListArtistAlbumForm laaf = new ListArtistAlbumForm();
        
        jMenu1.setEnabled(false);
        
        add(laaf,BorderLayout.CENTER);
        
        pack();    
    }//GEN-LAST:event_listArtistAlbumFormItemActionPerformed

    private void listPlayListFormItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listPlayListFormItemActionPerformed
        
        ListPlayListForm lplf = new ListPlayListForm();
        
        jMenu1.setEnabled(false);
        
        add(lplf,BorderLayout.CENTER);
  
        pack();       
    }//GEN-LAST:event_listPlayListFormItemActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem exitItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem listArtistAlbumFormItem;
    private javax.swing.JMenuItem listArtistFormItem;
    private javax.swing.JMenuItem listMusicGroupAlbumFormItem;
    private javax.swing.JMenuItem listMusicGroupFormItem;
    private javax.swing.JMenuItem listPlayListFormItem;
    // End of variables declaration//GEN-END:variables
}
