/* Διαγραφή πινάκων */

DROP TABLE PlayListSong;
DROP TABLE AlbumSong;
DROP TABLE MusicGroupArtist;
DROP TABLE PlayList;
DROP TABLE Album;
DROP TABLE MusicGroup;
DROP TABLE Artist;
DROP TABLE MusicGenre;
DROP TABLE MusicProductionCompany;
DROP TABLE Song;

/* Δημιουργία πινάκων */

CREATE TABLE MusicGenre (
    musicGenreID BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100)
);

CREATE TABLE MusicProductionCompany (
    MusicProductionCompanyID BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100),
    address VARCHAR(100),
    telephone VARCHAR(50)
);

CREATE TABLE Song (
    songID BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(100),
    duration BIGINT DEFAULT 0,
    trackNr BIGINT
);

CREATE TABLE Artist (
    artistID BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    firstName VARCHAR(50),
    lastName VARCHAR(50),
    artisticName VARCHAR(50),
    sex VARCHAR(10),
    birthDay VARCHAR(10),
    birthPlace VARCHAR(100),
    musicGenreID BIGINT,
    CONSTRAINT musicGenreArtistFK FOREIGN KEY (musicGenreID)
        REFERENCES MusicGenre(musicGenreID)
);

CREATE TABLE MusicGroup (
    musicGroupID BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100),
    formationDate VARCHAR(10)
);

CREATE TABLE MusicGroupArtist (
    MusicGroupArtistID BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    musicGroupID BIGINT,
    artistID BIGINT,    
    CONSTRAINT artistArtistMusicGroupFK FOREIGN KEY (artistID)
        REFERENCES Artist(artistID),
    CONSTRAINT musicGroupArtistMusicGroupFK FOREIGN KEY (musicGroupID)
        REFERENCES MusicGroup(musicGroupID)
);

CREATE TABLE Album (
    albumID BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(100),
    releaseDate VARCHAR(10),
    type VARCHAR(2),
    diskNumber BIGINT,
    musicProductionCompanyID BIGINT,
    artistID BIGINT,
    musicGroupID BIGINT,
    songID BIGINT,
    CONSTRAINT musicProductionCompanyAlbumFK FOREIGN KEY (musicProductionCompanyID) 
        REFERENCES MusicProductionCompany(musicProductionCompanyID),
    CONSTRAINT artistAlbumFK FOREIGN KEY (artistID) 
        REFERENCES Artist(artistID),
    CONSTRAINT musicGroupAlbumFK FOREIGN KEY (musicGroupID) 
        REFERENCES MusicGroup(musicGroupID),
    CONSTRAINT songAlbumFK FOREIGN KEY (songID) 
        REFERENCES Song(songID)
);

CREATE TABLE AlbumSong (
    AlbumSongID BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    albumID BIGINT,
    songID BIGINT,
    CONSTRAINT songSongAlbumFK FOREIGN KEY (songID) 
        REFERENCES Song(songID),
    CONSTRAINT albumSongAlbumFK FOREIGN KEY (albumID) 
        REFERENCES Album(albumID)
);

CREATE TABLE PlayList (
    playListID BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255)
);

CREATE TABLE PlayListSong (
    PlayListSongID BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    playListID BIGINT,
    songID BIGINT,
    CONSTRAINT songSongPlayListFK FOREIGN KEY (songID) 
        REFERENCES Song(songID),
    CONSTRAINT playListSongPlayListFK FOREIGN KEY (playListID) 
        REFERENCES PlayList(playListID)
);

/* Κάποιες εγγραφές για τον πίνακα MusicGenre */

INSERT INTO MusicGenre VALUES 
    (DEFAULT, 'Rock'),
    (DEFAULT, 'Classical'),
    (DEFAULT, 'Folk, World, & Country');

/* Κάποιες εγγραφές για τον πίνακα MusicProductionCompany */

INSERT INTO MusicProductionCompany VALUES 
    (DEFAULT, 'Capitol Records, Inc.', '1750 N. Vine Street, Hollywood, California 90028', '555-12345'),
    (DEFAULT, 'Warner Music Group Corp.', '75 Rockefeller Plz. Bsmt. 1, New York NY 10019-6990', '212-275-2000'),
    (DEFAULT, 'ATCO Records', '1290 Avenue of the Americas, New York, NY 10104, USA', '(800) 546-3670' );


/* Aλλαγές στους πίνακες */

ALTER TABLE Album ALTER diskNumber DEFAULT 1;
ALTER TABLE PlayList ADD COLUMN creationDate VARCHAR(10);